version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 1sampai8
    volumes:
      - ./db/fix.sql:/docker-entrypoint-initdb.d/fix.sql
    restart: on-failure

  web_pentest:
    build: web_for_pentest
    environment:
      DB: mysql
      LDAP: auth
    ports:
      - 1000:80
    
  dvwa:
    build: vulnerable-dvwa/
    environment:
      DB: mysql
    ports:
      - 2000:80

  bwapp:
    build: bWAPP
    environment:
      DB: mysql
    ports:
      - 3000:80
      
  auth:
    image: mlan/openldap:1
    restart: unless-stopped
    volumes:
      - ./web_for_pentest/seed:/var/lib/openldap/seed

  webgoat:
    image: webgoat/webgoat-8.0
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
      - TZ=Europe/Amsterdam
    ports:
      - "4000:8080"
    volumes:
      - ./webgoat:/home/webgoat/.webgoat
    working_dir: /home/webgoat
  webwolf:
    image: webgoat/webwolf
    ports:
      - "5000:9090"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
    depends_on:
            - webgoat